### ISSUE TITLE
Lift Motor Errors VexIQ

### ISSUE THREAD

**Issue by OneBiteAidan** [OneBiteAidan/VexIQ#1]
Trying to program the lift motor to go up and down with a corresponding button press. Getting lots of errors. No idea how to fix.

**Comment by KenwoodFox** [comment]
added curly brackets after all else and if statements
reformated motor commands from `if (vexRT[BtnLDown==1])` to `if (vexRT[BtnLDown] == 1)`
Cleaned up missing `;`
